name: Deploy Inputer Dashboard
on:
  push:
    branches: ["release"]
    
  # pull_request:
  #   branches: ["main"]
  
  workflow_dispatch:


jobs:
  deploy-service:
    runs-on: [self-hosted, Linux, X64, genahsehat]
    env:
      working-directory: form-vue
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Build app image
          run: ./create_form_img.sh

        - name: Create and run docker container
          run: docker compose up -d
              
